FROM node:22-alpine AS builder

WORKDIR /usr/src/app/app-ui

COPY . .
ENV NODE_OPTIONS=--openssl-legacy-provider

RUN npm ci --legacy-peer-deps && npm run build -- --prod

COPY . .

FROM nginx:alpine AS angular-ui

COPY --from=builder /usr/src/app/app-ui/dist/angular-nodejs-example /usr/share/nginx/html
EXPOSE 4201
